spring:
  cloud:
    gateway:
      routes:
        - id : r1
          uri: http://localhost:8081/api/customers
          predicates:
            - Path=/customers/**
        - id : r2
          uri: http://localhost:8082/api/accounts
          predicates:
            - Path=/accounts/**
  application:
    name: gateway-service
server:
  port: 8888
